import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { v4 as uuidv4 } from 'uuid'
import classNames from 'classnames'

const Home: NextPage = () => {

  // Tracks new item
  const [todoItem, setTodoItem] = useState({title: "", id: uuidv4(), done: false})

  // Tracks items in list
  const [items, setItems] = useState([])

  // Update value of new task when text is entered
  const handleChange = ({ target }) => {
    const { value } = target
    setTodoItem(prevTodoItem => ({...prevTodoItem, title: value, id: uuidv4(), done: false}))
  }

  // Add items to list
  const handleAdd = () => {
    // todoItem evaluates to false if it is an empty string
    if (todoItem.title) {
      setItems(prevItems => [todoItem, ...prevItems])
      // Clear text from field
      setTodoItem({title: "", id: "", done: false})
    }
    // TESTING
    makePostRequest()
    // END TESTING
  }

  // Track which items have been completed
  const handleToggle = (id: string) => {
    // Iterate through items and update the done status of the passed item
    setItems(prevItems => {
      return prevItems.map((item) => {
        if (item.id === id) {
          return {
            ...item,
            done: !item.done
          }
        }
        return item
      })
    })
    // TESTING
    makePostRequest()
    // END TESTING
  }

  // Make POST request to server storing todo items
  const makePostRequest = async() => {
    const myUrl = 'http://localhost:8080'
    const requestOptions = {
      method: 'POST',
      body: JSON.stringify(items)
    }
    const response = await fetch(myUrl, requestOptions)
    console.log(response)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Todo App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Please enter your tasks below.
        </h1>
        <br />

        <h2>To-Do:</h2>

        <input type="text" value={todoItem.title} onChange={handleChange} />
        <button type="button" onClick={handleAdd}>Add</button>
        
        <ul>
          {items.map(({ title, id, done }) => (
            <li 
              key={id} 
              onClick={() => handleToggle(id)}
              className={classNames({ 'done': done })}
            >
              {title} 
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default Home
